apiVersion: v1
kind: Service
metadata:
  name: mcp-test-stateless-server
  labels:
    app: mcp-test-stateless-server
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: mcp-test-stateless-server
  type: ClusterIP
