apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "broker-router.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "broker-router.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
