apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "broker-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "broker-router.labels" . | nindent 4 }}
automountServiceAccountToken: false
