package mcprouter

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"time"

	"github.com/Kuadrant/mcp-gateway/internal/elicitation"
	"golang.org/x/crypto/hkdf"
)

const userCredPrefix = "usercred:"

// UserTokenCache stores per-user tokens keyed by session and server name.
// Tokens are collected via URL elicitation and injected into upstream requests.
type UserTokenCache interface {
	// SetUserToken stores a token for the given session and server
	SetUserToken(ctx context.Context, sessionID, serverName, token string) error
	// GetUserToken retrieves a cached token. Returns ("", false, nil) on miss.
	// JWT tokens are checked for expiry; expired tokens are deleted and treated as a miss.
	// Opaque tokens (e.g. PATs) are returned without expiry checks.
	GetUserToken(ctx context.Context, sessionID, serverName string) (string, bool, error)
	// DeleteUserToken removes a cached token for the given session and server
	DeleteUserToken(ctx context.Context, sessionID, serverName string) error
	// Close stops background goroutines. Safe to call multiple times.
	Close()
}

// checkUpstreamJWTExpiry simple check of expiry, does not validate the JWT.
// Returns true if the token looks like a JWT and is expired.
// Non-JWT tokens (opaque PATs) return false.
func checkUpstreamJWTExpiry(token string) bool {
	var claims struct {
		Exp *float64 `json:"exp"`
	}
	if !elicitation.DecodeJWTPayload(token, &claims) || claims.Exp == nil {
		return false
	}
	return time.Unix(int64(*claims.Exp), 0).Before(time.Now())
}

// deriveEncryptionKey derives a 32-byte AES-256 key from the session signing key using HKDF
func deriveEncryptionKey(signingKey []byte) ([]byte, error) {
	if len(signingKey) < 16 {
		return nil, fmt.Errorf("signing key too short: need at least 16 bytes")
	}
	// nil salt is safe here — the signing key is a random key generated by the controller
	r := hkdf.New(sha256.New, signingKey, nil, []byte("mcp-gateway-user-token-encryption"))
	key := make([]byte, 32)
	if _, err := io.ReadFull(r, key); err != nil {
		return nil, fmt.Errorf("hkdf key derivation failed: %w", err)
	}
	return key, nil
}

func encrypt(key []byte, plaintext string) (string, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("encrypt: new cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("encrypt: new gcm: %w", err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", fmt.Errorf("encrypt: generating nonce: %w", err)
	}
	ciphertext := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

func decrypt(key []byte, encoded string) (string, error) {
	data, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return "", fmt.Errorf("decrypt: base64 decode: %w", err)
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("decrypt: new cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("decrypt: new gcm: %w", err)
	}
	nonceSize := gcm.NonceSize()
	if len(data) < nonceSize {
		return "", fmt.Errorf("decrypt: ciphertext too short")
	}
	plaintext, err := gcm.Open(nil, data[:nonceSize], data[nonceSize:], nil)
	if err != nil {
		return "", fmt.Errorf("decrypt: gcm open: %w", err)
	}
	return string(plaintext), nil
}
