name: Contributor Governance

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request_target:
    types: [opened, reopened]

jobs:
  governance:
    uses: Kuadrant/.github/.github/workflows/contributor-governance.yml@d1617682a51d84a48fbab0db932f380824284b48 # ratchet:Kuadrant/.github/.github/workflows/contributor-governance.yml@main
    secrets: inherit
