name: DCO-check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: DCO 
    runs-on: ubuntu-latest
    # This 'if' condition will only run the job if the actor is not dependabot[bot]
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Python 3.x
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'
      - name: Check DCO
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -U dco-check
          dco-check
