name: Spelling

on:
  pull_request:
    branches: [ 'main',  ]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: spelling-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run cspell with reviewdog
        uses: reviewdog/action-cspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: nofilter
          fail_on_error: true
          cspell_args: "--quiet ."
